version: '3'
services:
  db:
    image: "mysql:5.7"
    environment: 
      MYSQL_ROOT_PASSWORD: "1"
      MYSQL_DATABASE: "wallet_of_user"
    ports:
      - "3333:3306"
    command: ['mysqld', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci']
    volumes:
          - dbdata:/var/lib/mysql
volumes:
    dbdata: 